// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// d2root_cpp
arma::vec d2root_cpp(const int n, const arma::ivec node2parent, const arma::vec node2el);
RcppExport SEXP _garel_d2root_cpp(SEXP nSEXP, SEXP node2parentSEXP, SEXP node2elSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::ivec >::type node2parent(node2parentSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type node2el(node2elSEXP);
    rcpp_result_gen = Rcpp::wrap(d2root_cpp(n, node2parent, node2el));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_garel_d2root_cpp", (DL_FUNC) &_garel_d2root_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_garel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
