# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

d2root_cpp <- function(n, node2parent, node2el) {
    .Call('_garel_d2root_cpp', PACKAGE = 'garel', n, node2parent, node2el)
}

